import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class ProductsService {

constructor() { }
 Allproducts: any = [
  // ================= FOOTBALL SHOES =================
  {
    productId: 1,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "Cristiano Ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: true,
    inCart: false,
  },
  {
    productId: 2,
    productImage: "/messi-shoes.png",
    title: "Messi shoes",
    discription: "Lionel Messi adidas x-speed original",
    price: "480 LE",
    priceBeforediscount: "550 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: false,
    inCart: true,
  },
  {
    productId: 3,
    productImage: "/neymar-shoes.png",
    title: "Neymar shoes",
    discription: "Puma Neymar Jr football shoes",
    price: "430 LE",
    priceBeforediscount: "500 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: true,
    inCart: true,
  },
  {
    productId: 4,
    productImage: "/mbappe-shoes.png",
    title: "Mbappe shoes",
    discription: "Nike Mbappe mercurial vapor",
    price: "490 LE",
    priceBeforediscount: "560 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: false,
    inCart: false,
  },
  {
    productId: 5,
    productImage: "/salah-shoes.png",
    title: "Salah shoes",
    discription: "Original Adidas Salah speedflow",
    price: "470 LE",
    priceBeforediscount: "530 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: true,
    inCart: false,
  },
  {
    productId: 6,
    productImage: "/kane-shoes.png",
    title: "Harry Kane shoes",
    discription: "Nike Phantom GX Harry Kane edition",
    price: "460 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: false,
    inCart: true,
  },
  {
    productId: 7,
    productImage: "/benzema-shoes.png",
    title: "Benzema shoes",
    discription: "Adidas Karim Benzema predator",
    price: "500 LE",
    priceBeforediscount: "570 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: true,
    inCart: true,
  },
  {
    productId: 8,
    productImage: "/haaland-shoes.png",
    title: "Haaland shoes",
    discription: "Puma Haaland future ultimate",
    price: "510 LE",
    priceBeforediscount: "580 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: false,
    inCart: false,
  },
  {
    productId: 9,
    productImage: "/modric-shoes.png",
    title: "Modric shoes",
    discription: "Nike Tiempo Modric limited edition",
    price: "440 LE",
    priceBeforediscount: "500 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: true,
    inCart: false,
  },
  {
    productId: 10,
    productImage: "/iniesta-shoes.png",
    title: "Iniesta shoes",
    discription: "Asics Iniesta signature model",
    price: "420 LE",
    priceBeforediscount: "480 LE",
    categoryId: 2,
    categoryName: "Football shoes",
    isFavorite: false,
    inCart: true,
  },

  // ================= SPORTS ACCESSORIES =================
  {
    productId: 11,
    productImage: "/sock.png",
    title: "Al Ahly sock",
    discription: "Original cotton sock",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
    isFavorite: true,
    inCart: false,
  },
  {
    productId: 12,
    productImage: "/gloves.png",
    title: "Goalkeeper gloves",
    discription: "Adidas Predator Pro Gloves",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
    isFavorite: false,
    inCart: true,
  },
  {
    productId: 13,
    productImage: "/shin-guard.png",
    title: "Shin Guard",
    discription: "Nike Mercurial shin guard",
    price: "180 LE",
    priceBeforediscount: "220 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
    isFavorite: true,
    inCart: true,
  },
  {
    productId: 14,
    productImage: "/headband.png",
    title: "Headband",
    discription: "Cotton sweat headband",
    price: "90 LE",
    priceBeforediscount: "120 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
    isFavorite: false,
    inCart: false,
  },
  {
    productId: 15,
    productImage: "/cap.png",
    title: "Sports Cap",
    discription: "Adjustable breathable cap",
    price: "160 LE",
    priceBeforediscount: "210 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
    isFavorite: true,
    inCart: false,
  },

  // ================= SPORTS SHIRTS =================
  {
    productId: 16,
    productImage: "/arsenal-shirt.png",
    title: "Arsenal Shirt",
    discription: "Official Arsenal 24/25 home shirt",
    price: "380 LE",
    priceBeforediscount: "450 LE",
    categoryId: 3,
    categoryName: "Sports Shirts",
    isFavorite: true,
    inCart: true,
  },
  {
    productId: 17,
    productImage: "/barcelona-shirt.png",
    title: "Barcelona Shirt",
    discription: "Nike Barcelona home kit 24/25",
    price: "400 LE",
    priceBeforediscount: "470 LE",
    categoryId: 3,
    categoryName: "Sports Shirts",
    isFavorite: false,
    inCart: true,
  },
  {
    productId: 18,
    productImage: "/real-shirt.png",
    title: "Real Madrid Shirt",
    discription: "Adidas Real Madrid home 24/25",
    price: "420 LE",
    priceBeforediscount: "490 LE",
    categoryId: 3,
    categoryName: "Sports Shirts",
    isFavorite: true,
    inCart: false,
  },
  {
    productId: 19,
    productImage: "/liverpool-shirt.png",
    title: "Liverpool Shirt",
    discription: "Nike Liverpool home 24/25",
    price: "390 LE",
    priceBeforediscount: "460 LE",
    categoryId: 3,
    categoryName: "Sports Shirts",
    isFavorite: false,
    inCart: false,
  },
  {
    productId: 20,
    productImage: "/chelsea-shirt.png",
    title: "Chelsea Shirt",
    discription: "Nike Chelsea home shirt 24/25",
    price: "370 LE",
    priceBeforediscount: "440 LE",
    categoryId: 3,
    categoryName: "Sports Shirts",
    isFavorite: true,
    inCart: true,
  },

  // ================= FOOTBALL SHIRTS =================
  {
    productId: 21,
    productImage: "/brazil-shirt.png",
    title: "Brazil Shirt",
    discription: "Nike Brazil national team shirt",
    price: "360 LE",
    priceBeforediscount: "420 LE",
    categoryId: 1,
    categoryName: "Football Shirts",
    isFavorite: true,
    inCart: false,
  },
  {
    productId: 22,
    productImage: "/germany-shirt.png",
    title: "Germany Shirt",
    discription: "Adidas Germany Euro 2024 kit",
    price: "370 LE",
    priceBeforediscount: "430 LE",
    categoryId: 1,
    categoryName: "Football Shirts",
    isFavorite: false,
    inCart: true,
  },
  {
    productId: 23,
    productImage: "/argentina-shirt.png",
    title: "Argentina Shirt",
    discription: "Adidas Argentina Messi shirt",
    price: "400 LE",
    priceBeforediscount: "470 LE",
    categoryId: 1,
    categoryName: "Football Shirts",
    isFavorite: true,
    inCart: true,
  },
  {
    productId: 24,
    productImage: "/france-shirt.png",
    title: "France Shirt",
    discription: "Nike France home shirt",
    price: "380 LE",
    priceBeforediscount: "450 LE",
    categoryId: 1,
    categoryName: "Football Shirts",
    isFavorite: false,
    inCart: false,
  },
  {
    productId: 25,
    productImage: "/egypt-shirt.png",
    title: "Egypt Shirt",
    discription: "Puma Egypt national team kit",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 1,
    categoryName: "Football Shirts",
    isFavorite: true,
    inCart: false,
  },

  // ================= SPORTS BAGS =================
  {
    productId: 26,
    productImage: "/nike-bag.png",
    title: "Nike Sports Bag",
    discription: "Nike medium duffle training bag",
    price: "300 LE",
    priceBeforediscount: "360 LE",
    categoryId: 6,
    categoryName: "Sports Bags",
    isFavorite: true,
    inCart: false,
  },
  {
    productId: 27,
    productImage: "/adidas-bag.png",
    title: "Adidas Backpack",
    discription: "Adidas Tiro football backpack",
    price: "320 LE",
    priceBeforediscount: "390 LE",
    categoryId: 6,
    categoryName: "Sports Bags",
    isFavorite: false,
    inCart: true,
  },
  {
    productId: 28,
    productImage: "/puma-bag.png",
    title: "Puma Training Bag",
    discription: "Puma gym duffle bag",
    price: "280 LE",
    priceBeforediscount: "340 LE",
    categoryId: 6,
    categoryName: "Sports Bags",
    isFavorite: true,
    inCart: true,
  },
  {
    productId: 29,
    productImage: "/jordan-bag.png",
    title: "Jordan Bag",
    discription: "Jordan basketball backpack",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports Bags",
    isFavorite: false,
    inCart: false,
  },
  {
    productId: 30,
    productImage: "/umbro-bag.png",
    title: "Umbro Bag",
    discription: "Umbro football travel bag",
    price: "270 LE",
    priceBeforediscount: "330 LE",
    categoryId: 6,
    categoryName: "Sports Bags",
    isFavorite: true,
    inCart: false,
  },
  // Allproducts (part 2: 35 → 68)

// Football T-shirts
{
  productId: 35,
  productImage: "/tshirt.png",
  title: "Al Ahly T-shirt",
  discription: "Official club T-shirt",
  price: "650 LE",
  priceBeforediscount: "750 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: false,
},
{
  productId: 36,
  productImage: "/tshirt.png",
  title: "Zamalek T-shirt",
  discription: "Official club T-shirt",
  price: "620 LE",
  priceBeforediscount: "700 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: true,
},
{
  productId: 37,
  productImage: "/tshirt.png",
  title: "Barcelona T-shirt",
  discription: "Original club T-shirt",
  price: "700 LE",
  priceBeforediscount: "820 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: true,
},
{
  productId: 38,
  productImage: "/tshirt.png",
  title: "Real Madrid T-shirt",
  discription: "Original club T-shirt",
  price: "690 LE",
  priceBeforediscount: "800 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: false,
},

// Football shoes extra
{
  productId: 39,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: true,
  inCart: false,
},
{
  productId: 40,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: false,
  inCart: true,
},
{
  productId: 41,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: true,
  inCart: true,
},
{
  productId: 42,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: false,
  inCart: false,
},

// Sports Accessories more
{
  productId: 43,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: true,
  inCart: false,
},
{
  productId: 44,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: false,
  inCart: true,
},
{
  productId: 45,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: false,
  inCart: false,
},
{
  productId: 46,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: true,
  inCart: true,
},

// More T-shirts
{
  productId: 47,
  productImage: "/tshirt.png",
  title: "Egypt National Team T-shirt",
  discription: "Official Egypt kit",
  price: "670 LE",
  priceBeforediscount: "750 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: false,
},
{
  productId: 48,
  productImage: "/tshirt.png",
  title: "Argentina T-shirt",
  discription: "Official Argentina kit",
  price: "680 LE",
  priceBeforediscount: "770 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: true,
},
// Allproducts (part 2: 35 → 68)

// Football T-shirts
{
  productId: 35,
  productImage: "/tshirt.png",
  title: "Al Ahly T-shirt",
  discription: "Official club T-shirt",
  price: "650 LE",
  priceBeforediscount: "750 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: false,
},
{
  productId: 36,
  productImage: "/tshirt.png",
  title: "Zamalek T-shirt",
  discription: "Official club T-shirt",
  price: "620 LE",
  priceBeforediscount: "700 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: true,
},
{
  productId: 37,
  productImage: "/tshirt.png",
  title: "Barcelona T-shirt",
  discription: "Original club T-shirt",
  price: "700 LE",
  priceBeforediscount: "820 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: true,
},
{
  productId: 38,
  productImage: "/tshirt.png",
  title: "Real Madrid T-shirt",
  discription: "Original club T-shirt",
  price: "690 LE",
  priceBeforediscount: "800 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: false,
},

// Football shoes extra
{
  productId: 39,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: true,
  inCart: false,
},
{
  productId: 40,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: false,
  inCart: true,
},
{
  productId: 41,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: true,
  inCart: true,
},
{
  productId: 42,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: false,
  inCart: false,
},

// Sports Accessories more
{
  productId: 43,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: true,
  inCart: false,
},
{
  productId: 44,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: false,
  inCart: true,
},
{
  productId: 45,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: false,
  inCart: false,
},
{
  productId: 46,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: true,
  inCart: true,
},

// More T-shirts
{
  productId: 47,
  productImage: "/tshirt.png",
  title: "Egypt National Team T-shirt",
  discription: "Official Egypt kit",
  price: "670 LE",
  priceBeforediscount: "750 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: false,
},
{
  productId: 48,
  productImage: "/tshirt.png",
  title: "Argentina T-shirt",
  discription: "Official Argentina kit",
  price: "680 LE",
  priceBeforediscount: "770 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: true,
},

// ... تكملة لغاية المنتج 68
// Allproducts (part 2: 35 → 68)

// Football T-shirts
{
  productId: 35,
  productImage: "/tshirt.png",
  title: "Al Ahly T-shirt",
  discription: "Official club T-shirt",
  price: "650 LE",
  priceBeforediscount: "750 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: false,
},
{
  productId: 36,
  productImage: "/tshirt.png",
  title: "Zamalek T-shirt",
  discription: "Official club T-shirt",
  price: "620 LE",
  priceBeforediscount: "700 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: true,
},
{
  productId: 37,
  productImage: "/tshirt.png",
  title: "Barcelona T-shirt",
  discription: "Original club T-shirt",
  price: "700 LE",
  priceBeforediscount: "820 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: true,
},
{
  productId: 38,
  productImage: "/tshirt.png",
  title: "Real Madrid T-shirt",
  discription: "Original club T-shirt",
  price: "690 LE",
  priceBeforediscount: "800 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: false,
},

// Football shoes extra
{
  productId: 39,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: true,
  inCart: false,
},
{
  productId: 40,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: false,
  inCart: true,
},
{
  productId: 41,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: true,
  inCart: true,
},
{
  productId: 42,
  productImage: "/messi-shoes.png",
  title: "Messi shoes",
  discription: "lionel messi original shoes",
  price: "480 LE",
  priceBeforediscount: "550 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: false,
  inCart: false,
},

// Sports Accessories more
{
  productId: 43,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: true,
  inCart: false,
},
{
  productId: 44,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: false,
  inCart: true,
},
{
  productId: 45,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: false,
  inCart: false,
},
{
  productId: 46,
  productImage: "/gloves.png",
  title: "Goalkeeper Gloves",
  discription: "High quality gloves",
  price: "300 LE",
  priceBeforediscount: "370 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: true,
  inCart: true,
},

// More T-shirts
{
  productId: 47,
  productImage: "/tshirt.png",
  title: "Egypt National Team T-shirt",
  discription: "Official Egypt kit",
  price: "670 LE",
  priceBeforediscount: "750 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: false,
},
{
  productId: 48,
  productImage: "/tshirt.png",
  title: "Argentina T-shirt",
  discription: "Official Argentina kit",
  price: "680 LE",
  priceBeforediscount: "770 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: true,
},

// Allproducts (part 3: 49 → 68)

// Football T-shirts continued
{
  productId: 49,
  productImage: "/tshirt.png",
  title: "France T-shirt",
  discription: "Official France kit",
  price: "700 LE",
  priceBeforediscount: "780 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: false,
},
{
  productId: 50,
  productImage: "/tshirt.png",
  title: "Brazil T-shirt",
  discription: "Official Brazil kit",
  price: "710 LE",
  priceBeforediscount: "790 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: true,
},
{
  productId: 51,
  productImage: "/tshirt.png",
  title: "Germany T-shirt",
  discription: "Official Germany kit",
  price: "720 LE",
  priceBeforediscount: "800 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: false,
},
{
  productId: 52,
  productImage: "/tshirt.png",
  title: "Manchester United T-shirt",
  discription: "Official Man United kit",
  price: "740 LE",
  priceBeforediscount: "820 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: true,
},

// Football shoes extra
{
  productId: 53,
  productImage: "/neymar-shoes.png",
  title: "Neymar shoes",
  discription: "Neymar official edition",
  price: "500 LE",
  priceBeforediscount: "580 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: true,
  inCart: false,
},
{
  productId: 54,
  productImage: "/neymar-shoes.png",
  title: "Neymar shoes",
  discription: "Neymar official edition",
  price: "500 LE",
  priceBeforediscount: "580 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: false,
  inCart: true,
},
{
  productId: 55,
  productImage: "/neymar-shoes.png",
  title: "Neymar shoes",
  discription: "Neymar official edition",
  price: "500 LE",
  priceBeforediscount: "580 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: false,
  inCart: false,
},
{
  productId: 56,
  productImage: "/neymar-shoes.png",
  title: "Neymar shoes",
  discription: "Neymar official edition",
  price: "500 LE",
  priceBeforediscount: "580 LE",
  categoryId: 2,
  categoryName: "Football shoes",
  isFavorite: true,
  inCart: true,
},

// Sports Accessories continued
{
  productId: 57,
  productImage: "/cap.png",
  title: "Sports Cap",
  discription: "Lightweight training cap",
  price: "180 LE",
  priceBeforediscount: "230 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: true,
  inCart: false,
},
{
  productId: 58,
  productImage: "/cap.png",
  title: "Sports Cap",
  discription: "Lightweight training cap",
  price: "180 LE",
  priceBeforediscount: "230 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: false,
  inCart: true,
},
{
  productId: 59,
  productImage: "/cap.png",
  title: "Sports Cap",
  discription: "Lightweight training cap",
  price: "180 LE",
  priceBeforediscount: "230 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: false,
  inCart: false,
},
{
  productId: 60,
  productImage: "/cap.png",
  title: "Sports Cap",
  discription: "Lightweight training cap",
  price: "180 LE",
  priceBeforediscount: "230 LE",
  categoryId: 5,
  categoryName: "Sports Accessories",
  isFavorite: true,
  inCart: true,
},

// Final batch of T-shirts
{
  productId: 61,
  productImage: "/tshirt.png",
  title: "Liverpool T-shirt",
  discription: "Official Liverpool kit",
  price: "730 LE",
  priceBeforediscount: "820 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: false,
},
{
  productId: 62,
  productImage: "/tshirt.png",
  title: "Chelsea T-shirt",
  discription: "Official Chelsea kit",
  price: "740 LE",
  priceBeforediscount: "830 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: true,
},
{
  productId: 63,
  productImage: "/tshirt.png",
  title: "AC Milan T-shirt",
  discription: "Official AC Milan kit",
  price: "710 LE",
  priceBeforediscount: "800 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: false,
},
{
  productId: 64,
  productImage: "/tshirt.png",
  title: "Inter Milan T-shirt",
  discription: "Official Inter kit",
  price: "720 LE",
  priceBeforediscount: "810 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: true,
},
{
  productId: 65,
  productImage: "/tshirt.png",
  title: "Arsenal T-shirt",
  discription: "Official Arsenal kit",
  price: "700 LE",
  priceBeforediscount: "790 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: false,
},
{
  productId: 66,
  productImage: "/tshirt.png",
  title: "Tottenham T-shirt",
  discription: "Official Spurs kit",
  price: "690 LE",
  priceBeforediscount: "770 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: true,
},
{
  productId: 67,
  productImage: "/tshirt.png",
  title: "Juventus T-shirt",
  discription: "Official Juventus kit",
  price: "710 LE",
  priceBeforediscount: "790 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: false,
  inCart: false,
},
{
  productId: 68,
  productImage: "/tshirt.png",
  title: "PSG T-shirt",
  discription: "Official PSG kit",
  price: "720 LE",
  priceBeforediscount: "800 LE",
  categoryId: 1,
  categoryName: "Sports T-shirts",
  isFavorite: true,
  inCart: true,
},




];



    getAll(){
        return [...this.Allproducts]
    }

    getCategoryProducts(categoryId:number){
        return this.Allproducts.filter((prd:any)=>{
            return prd.categoryId===categoryId
        })
    }


}
