import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class ProductsService {

constructor() { }
    Allproducts: any = [
  // Football shoes
  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },

  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },

  //*********************Sports Accessorires
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },
  {
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessorires",
  },

  //*********************************************************************** */Sports bags
  {
    id: 1,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },

  {
    id: 1,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    id: 1,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },

  {
    id: 1,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    id: 2,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    id: 3,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    id: 4,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    id: 5,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    id: 6,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    id: 7,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    id: 8,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },

  //************************************************* */Sports shoes
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },

  //********************************************* */ Sports tshirts
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },

  //********************************* T-shirts */
  {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
   {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
   {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
   {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
   {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
];

    getAll(){
        return [...this.Allproducts]
    }

    getCategoryProducts(categoryId:number){
        return this.Allproducts.filter((prd:any)=>{
            return prd.categoryId===categoryId
        })
    }


}
