import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class ProductsService {

constructor() { }
  Allproducts: any = [
  // Football shoes
  {
    productId: 1,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productId: 2,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productId: 3,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productId: 4,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productId: 5,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productId: 6,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productId: 7,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productId: 8,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productId: 9,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },
  {
    productId: 10,
    productImage: "/cr7-shoes.png",
    title: "CR7 shoes",
    discription: "cristiano ronaldo original shoes",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 2,
    categoryName: "Football shoes",
  },

  // Sports Accessories
  {
    productId: 11,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 12,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 13,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 14,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 15,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 16,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 17,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 18,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 19,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 20,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 21,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },
  {
    productId: 22,
    productImage: "/sock.png",
    title: "Al ahly sock",
    discription: "original cotton sock ",
    price: "150 LE",
    priceBeforediscount: "200 LE",
    categoryId: 5,
    categoryName: "Sports Accessories",
  },

  // Sports bags
  {
    productId: 23,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 24,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 25,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 26,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 27,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 28,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 29,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 30,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 31,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 32,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 33,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },
  {
    productId: 34,
    productImage: "/new-bag.png",
    title: "bracelona bag",
    discription: "original cotton braca bag",
    price: "350 LE",
    priceBeforediscount: "420 LE",
    categoryId: 6,
    categoryName: "Sports bags",
  },

  // Sports shoes
  {
    productId: 35,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 36,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 37,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 38,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 39,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 40,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 41,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 42,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 43,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 44,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },
  {
    productId: 45,
    productImage: "/sports-shoes.png",
    title: "sports shoes",
    discription: " original shoes with high quality ...",
    price: "450 LE",
    priceBeforediscount: "520 LE",
    categoryId: 4,
    categoryName: "Sports shoes",
  },

  // Sports tshirts
  {
    productId: 46,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 47,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 48,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 49,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 50,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 51,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 52,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 53,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 54,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 55,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 56,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },
  {
    productId: 57,
    productImage: "/arsenal-shirt.svg",
    title: "Arsenal shirt",
    discription: " original arsenal tshirt ...",
    price: "290 LE",
    priceBeforediscount: "320 LE",
    categoryId: 1,
    categoryName: "Sports tshirts",
  },

  // T-shirts
  {
    productId: 58,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 59,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 60,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 61,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 62,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 63,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 64,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 65,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 66,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 67,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
  {
    productId: 68,
    productImage: "/tshirt.png",
    title: "cotton shirt",
    discription: " original cotton t-shirt with ...",
    price: "550 LE",
    priceBeforediscount: "720 LE",
    categoryId: 3,
    categoryName: "T-shirts",
  },
];


    getAll(){
        return [...this.Allproducts]
    }

    getCategoryProducts(categoryId:number){
        return this.Allproducts.filter((prd:any)=>{
            return prd.categoryId===categoryId
        })
    }


}
